<?php

// Mapping mode: jQuery

$__obj=Array('obj'=>Array(),'call'=>Array());

class PHFunction{
	public $_id;
	public $_type='function';
	public $_code;
	function __construct($code) {  global $__obj; $this->_code=$code; array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	function _serialize(){ return Array('_id'=>$this->_id,'_type'=>'function','code'=>$this->_code); }
}

class PHDiv{
	private $_main=false;
	public $_id;
	private $_type='div';
	public $jquery;
	public $selector;
	public function __construct() { global $__obj;array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	private function _call($fn,$a) { global $__obj;$args=Array(); for ($i=0;$i<count($a);$i++) array_push($args,is_object($a[$i])&&$a[$i]->_id?Array('_'=>$a[$i]->_id):$a[$i]); array_push($__obj['call'],Array($this->_id,$fn,$args)); }
	function _serialize(){ $out=Array(); foreach ($this as $k=>$v) if (isset($this->$k)) $out[$k]=$this->$k; return $out; }
	function done(){ global $__obj; $this->_main=true; $out=Array('call'=>$__obj['call'],'obj'=>Array()); for ($i=0;$i<count($__obj['obj']);$i++) $out['obj'][$i]=$__obj['obj'][$i]->_serialize(); echo json_encode($out); }
	function init(){ $this->_call('init',func_get_args()); return $this; }
	function size(){ $this->_call('size',func_get_args()); return $this; }
	function toArray(){ $this->_call('toArray',func_get_args()); return $this; }
	function get(){ $this->_call('get',func_get_args()); return $this; }
	function pushStack(){ $this->_call('pushStack',func_get_args()); return $this; }
	function each(){ $this->_call('each',func_get_args()); return $this; }
	function ready(){ $this->_call('ready',func_get_args()); return $this; }
	function slice(){ $this->_call('slice',func_get_args()); return $this; }
	function first(){ $this->_call('first',func_get_args()); return $this; }
	function last(){ $this->_call('last',func_get_args()); return $this; }
	function eq(){ $this->_call('eq',func_get_args()); return $this; }
	function map(){ $this->_call('map',func_get_args()); return $this; }
	function end(){ $this->_call('end',func_get_args()); return $this; }
	function push(){ $this->_call('push',func_get_args()); return $this; }
	function sort(){ $this->_call('sort',func_get_args()); return $this; }
	function splice(){ $this->_call('splice',func_get_args()); return $this; }
	function extend(){ $this->_call('extend',func_get_args()); return $this; }
	function data(){ $this->_call('data',func_get_args()); return $this; }
	function removeData(){ $this->_call('removeData',func_get_args()); return $this; }
	function queue(){ $this->_call('queue',func_get_args()); return $this; }
	function dequeue(){ $this->_call('dequeue',func_get_args()); return $this; }
	function delay(){ $this->_call('delay',func_get_args()); return $this; }
	function clearQueue(){ $this->_call('clearQueue',func_get_args()); return $this; }
	function promise(){ $this->_call('promise',func_get_args()); return $this; }
	function attr(){ $this->_call('attr',func_get_args()); return $this; }
	function removeAttr(){ $this->_call('removeAttr',func_get_args()); return $this; }
	function prop(){ $this->_call('prop',func_get_args()); return $this; }
	function removeProp(){ $this->_call('removeProp',func_get_args()); return $this; }
	function addClass(){ $this->_call('addClass',func_get_args()); return $this; }
	function removeClass(){ $this->_call('removeClass',func_get_args()); return $this; }
	function toggleClass(){ $this->_call('toggleClass',func_get_args()); return $this; }
	function hasClass(){ $this->_call('hasClass',func_get_args()); return $this; }
	function val(){ $this->_call('val',func_get_args()); return $this; }
	function on(){ $this->_call('on',func_get_args()); return $this; }
	function one(){ $this->_call('one',func_get_args()); return $this; }
	function off(){ $this->_call('off',func_get_args()); return $this; }
	function bind(){ $this->_call('bind',func_get_args()); return $this; }
	function unbind(){ $this->_call('unbind',func_get_args()); return $this; }
	function delegate(){ $this->_call('delegate',func_get_args()); return $this; }
	function undelegate(){ $this->_call('undelegate',func_get_args()); return $this; }
	function trigger(){ $this->_call('trigger',func_get_args()); return $this; }
	function triggerHandler(){ $this->_call('triggerHandler',func_get_args()); return $this; }
	function find(){ $this->_call('find',func_get_args()); return $this; }
	function has(){ $this->_call('has',func_get_args()); return $this; }
	function not(){ $this->_call('not',func_get_args()); return $this; }
	function filter(){ $this->_call('filter',func_get_args()); return $this; }
	function is(){ $this->_call('is',func_get_args()); return $this; }
	function closest(){ $this->_call('closest',func_get_args()); return $this; }
	function index(){ $this->_call('index',func_get_args()); return $this; }
	function add(){ $this->_call('add',func_get_args()); return $this; }
	function addBack(){ $this->_call('addBack',func_get_args()); return $this; }
	function andSelf(){ $this->_call('andSelf',func_get_args()); return $this; }
	function parent(){ $this->_call('parent',func_get_args()); return $this; }
	function parents(){ $this->_call('parents',func_get_args()); return $this; }
	function parentsUntil(){ $this->_call('parentsUntil',func_get_args()); return $this; }
	function next(){ $this->_call('next',func_get_args()); return $this; }
	function prev(){ $this->_call('prev',func_get_args()); return $this; }
	function nextAll(){ $this->_call('nextAll',func_get_args()); return $this; }
	function prevAll(){ $this->_call('prevAll',func_get_args()); return $this; }
	function nextUntil(){ $this->_call('nextUntil',func_get_args()); return $this; }
	function prevUntil(){ $this->_call('prevUntil',func_get_args()); return $this; }
	function siblings(){ $this->_call('siblings',func_get_args()); return $this; }
	function children(){ $this->_call('children',func_get_args()); return $this; }
	function contents(){ $this->_call('contents',func_get_args()); return $this; }
	function text(){ $this->_call('text',func_get_args()); return $this; }
	function wrapAll(){ $this->_call('wrapAll',func_get_args()); return $this; }
	function wrapInner(){ $this->_call('wrapInner',func_get_args()); return $this; }
	function wrap(){ $this->_call('wrap',func_get_args()); return $this; }
	function unwrap(){ $this->_call('unwrap',func_get_args()); return $this; }
	function append(){ $this->_call('append',func_get_args()); return $this; }
	function prepend(){ $this->_call('prepend',func_get_args()); return $this; }
	function before(){ $this->_call('before',func_get_args()); return $this; }
	function after(){ $this->_call('after',func_get_args()); return $this; }
	function remove(){ $this->_call('remove',func_get_args()); return $this; }
	function phempty(){ $this->_call('empty',func_get_args()); return $this; }
	function phclone(){ $this->_call('clone',func_get_args()); return $this; }
	function html(){ $this->_call('html',func_get_args()); return $this; }
	function replaceWith(){ $this->_call('replaceWith',func_get_args()); return $this; }
	function detach(){ $this->_call('detach',func_get_args()); return $this; }
	function domManip(){ $this->_call('domManip',func_get_args()); return $this; }
	function appendTo(){ $this->_call('appendTo',func_get_args()); return $this; }
	function prependTo(){ $this->_call('prependTo',func_get_args()); return $this; }
	function insertBefore(){ $this->_call('insertBefore',func_get_args()); return $this; }
	function insertAfter(){ $this->_call('insertAfter',func_get_args()); return $this; }
	function replaceAll(){ $this->_call('replaceAll',func_get_args()); return $this; }
	function css(){ $this->_call('css',func_get_args()); return $this; }
	function show(){ $this->_call('show',func_get_args()); return $this; }
	function hide(){ $this->_call('hide',func_get_args()); return $this; }
	function toggle(){ $this->_call('toggle',func_get_args()); return $this; }
	function serialize(){ $this->_call('serialize',func_get_args()); return $this; }
	function serializeArray(){ $this->_call('serializeArray',func_get_args()); return $this; }
	function blur(){ $this->_call('blur',func_get_args()); return $this; }
	function focus(){ $this->_call('focus',func_get_args()); return $this; }
	function focusin(){ $this->_call('focusin',func_get_args()); return $this; }
	function focusout(){ $this->_call('focusout',func_get_args()); return $this; }
	function load(){ $this->_call('load',func_get_args()); return $this; }
	function resize(){ $this->_call('resize',func_get_args()); return $this; }
	function scroll(){ $this->_call('scroll',func_get_args()); return $this; }
	function unload(){ $this->_call('unload',func_get_args()); return $this; }
	function click(){ $this->_call('click',func_get_args()); return $this; }
	function dblclick(){ $this->_call('dblclick',func_get_args()); return $this; }
	function mousedown(){ $this->_call('mousedown',func_get_args()); return $this; }
	function mouseup(){ $this->_call('mouseup',func_get_args()); return $this; }
	function mousemove(){ $this->_call('mousemove',func_get_args()); return $this; }
	function mouseover(){ $this->_call('mouseover',func_get_args()); return $this; }
	function mouseout(){ $this->_call('mouseout',func_get_args()); return $this; }
	function mouseenter(){ $this->_call('mouseenter',func_get_args()); return $this; }
	function mouseleave(){ $this->_call('mouseleave',func_get_args()); return $this; }
	function change(){ $this->_call('change',func_get_args()); return $this; }
	function select(){ $this->_call('select',func_get_args()); return $this; }
	function submit(){ $this->_call('submit',func_get_args()); return $this; }
	function keydown(){ $this->_call('keydown',func_get_args()); return $this; }
	function keypress(){ $this->_call('keypress',func_get_args()); return $this; }
	function keyup(){ $this->_call('keyup',func_get_args()); return $this; }
	function error(){ $this->_call('error',func_get_args()); return $this; }
	function contextmenu(){ $this->_call('contextmenu',func_get_args()); return $this; }
	function hover(){ $this->_call('hover',func_get_args()); return $this; }
	function ajaxStart(){ $this->_call('ajaxStart',func_get_args()); return $this; }
	function ajaxStop(){ $this->_call('ajaxStop',func_get_args()); return $this; }
	function ajaxComplete(){ $this->_call('ajaxComplete',func_get_args()); return $this; }
	function ajaxError(){ $this->_call('ajaxError',func_get_args()); return $this; }
	function ajaxSuccess(){ $this->_call('ajaxSuccess',func_get_args()); return $this; }
	function ajaxSend(){ $this->_call('ajaxSend',func_get_args()); return $this; }
	function fadeTo(){ $this->_call('fadeTo',func_get_args()); return $this; }
	function animate(){ $this->_call('animate',func_get_args()); return $this; }
	function stop(){ $this->_call('stop',func_get_args()); return $this; }
	function finish(){ $this->_call('finish',func_get_args()); return $this; }
	function slideDown(){ $this->_call('slideDown',func_get_args()); return $this; }
	function slideUp(){ $this->_call('slideUp',func_get_args()); return $this; }
	function slideToggle(){ $this->_call('slideToggle',func_get_args()); return $this; }
	function fadeIn(){ $this->_call('fadeIn',func_get_args()); return $this; }
	function fadeOut(){ $this->_call('fadeOut',func_get_args()); return $this; }
	function fadeToggle(){ $this->_call('fadeToggle',func_get_args()); return $this; }
	function offset(){ $this->_call('offset',func_get_args()); return $this; }
	function position(){ $this->_call('position',func_get_args()); return $this; }
	function offsetParent(){ $this->_call('offsetParent',func_get_args()); return $this; }
	function scrollLeft(){ $this->_call('scrollLeft',func_get_args()); return $this; }
	function scrollTop(){ $this->_call('scrollTop',func_get_args()); return $this; }
	function innerHeight(){ $this->_call('innerHeight',func_get_args()); return $this; }
	function height(){ $this->_call('height',func_get_args()); return $this; }
	function outerHeight(){ $this->_call('outerHeight',func_get_args()); return $this; }
	function innerWidth(){ $this->_call('innerWidth',func_get_args()); return $this; }
	function width(){ $this->_call('width',func_get_args()); return $this; }
	function outerWidth(){ $this->_call('outerWidth',func_get_args()); return $this; }
}

class PHTable{
	private $_main=false;
	public $_id;
	private $_type='table';
	public $jquery;
	public $selector;
	public function __construct() { global $__obj;array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	private function _call($fn,$a) { global $__obj;$args=Array(); for ($i=0;$i<count($a);$i++) array_push($args,is_object($a[$i])&&$a[$i]->_id?Array('_'=>$a[$i]->_id):$a[$i]); array_push($__obj['call'],Array($this->_id,$fn,$args)); }
	function _serialize(){ $out=Array(); foreach ($this as $k=>$v) if (isset($this->$k)) $out[$k]=$this->$k; return $out; }
	function done(){ global $__obj; $this->_main=true; $out=Array('call'=>$__obj['call'],'obj'=>Array()); for ($i=0;$i<count($__obj['obj']);$i++) $out['obj'][$i]=$__obj['obj'][$i]->_serialize(); echo json_encode($out); }
	function init(){ $this->_call('init',func_get_args()); return $this; }
	function size(){ $this->_call('size',func_get_args()); return $this; }
	function toArray(){ $this->_call('toArray',func_get_args()); return $this; }
	function get(){ $this->_call('get',func_get_args()); return $this; }
	function pushStack(){ $this->_call('pushStack',func_get_args()); return $this; }
	function each(){ $this->_call('each',func_get_args()); return $this; }
	function ready(){ $this->_call('ready',func_get_args()); return $this; }
	function slice(){ $this->_call('slice',func_get_args()); return $this; }
	function first(){ $this->_call('first',func_get_args()); return $this; }
	function last(){ $this->_call('last',func_get_args()); return $this; }
	function eq(){ $this->_call('eq',func_get_args()); return $this; }
	function map(){ $this->_call('map',func_get_args()); return $this; }
	function end(){ $this->_call('end',func_get_args()); return $this; }
	function push(){ $this->_call('push',func_get_args()); return $this; }
	function sort(){ $this->_call('sort',func_get_args()); return $this; }
	function splice(){ $this->_call('splice',func_get_args()); return $this; }
	function extend(){ $this->_call('extend',func_get_args()); return $this; }
	function data(){ $this->_call('data',func_get_args()); return $this; }
	function removeData(){ $this->_call('removeData',func_get_args()); return $this; }
	function queue(){ $this->_call('queue',func_get_args()); return $this; }
	function dequeue(){ $this->_call('dequeue',func_get_args()); return $this; }
	function delay(){ $this->_call('delay',func_get_args()); return $this; }
	function clearQueue(){ $this->_call('clearQueue',func_get_args()); return $this; }
	function promise(){ $this->_call('promise',func_get_args()); return $this; }
	function attr(){ $this->_call('attr',func_get_args()); return $this; }
	function removeAttr(){ $this->_call('removeAttr',func_get_args()); return $this; }
	function prop(){ $this->_call('prop',func_get_args()); return $this; }
	function removeProp(){ $this->_call('removeProp',func_get_args()); return $this; }
	function addClass(){ $this->_call('addClass',func_get_args()); return $this; }
	function removeClass(){ $this->_call('removeClass',func_get_args()); return $this; }
	function toggleClass(){ $this->_call('toggleClass',func_get_args()); return $this; }
	function hasClass(){ $this->_call('hasClass',func_get_args()); return $this; }
	function val(){ $this->_call('val',func_get_args()); return $this; }
	function on(){ $this->_call('on',func_get_args()); return $this; }
	function one(){ $this->_call('one',func_get_args()); return $this; }
	function off(){ $this->_call('off',func_get_args()); return $this; }
	function bind(){ $this->_call('bind',func_get_args()); return $this; }
	function unbind(){ $this->_call('unbind',func_get_args()); return $this; }
	function delegate(){ $this->_call('delegate',func_get_args()); return $this; }
	function undelegate(){ $this->_call('undelegate',func_get_args()); return $this; }
	function trigger(){ $this->_call('trigger',func_get_args()); return $this; }
	function triggerHandler(){ $this->_call('triggerHandler',func_get_args()); return $this; }
	function find(){ $this->_call('find',func_get_args()); return $this; }
	function has(){ $this->_call('has',func_get_args()); return $this; }
	function not(){ $this->_call('not',func_get_args()); return $this; }
	function filter(){ $this->_call('filter',func_get_args()); return $this; }
	function is(){ $this->_call('is',func_get_args()); return $this; }
	function closest(){ $this->_call('closest',func_get_args()); return $this; }
	function index(){ $this->_call('index',func_get_args()); return $this; }
	function add(){ $this->_call('add',func_get_args()); return $this; }
	function addBack(){ $this->_call('addBack',func_get_args()); return $this; }
	function andSelf(){ $this->_call('andSelf',func_get_args()); return $this; }
	function parent(){ $this->_call('parent',func_get_args()); return $this; }
	function parents(){ $this->_call('parents',func_get_args()); return $this; }
	function parentsUntil(){ $this->_call('parentsUntil',func_get_args()); return $this; }
	function next(){ $this->_call('next',func_get_args()); return $this; }
	function prev(){ $this->_call('prev',func_get_args()); return $this; }
	function nextAll(){ $this->_call('nextAll',func_get_args()); return $this; }
	function prevAll(){ $this->_call('prevAll',func_get_args()); return $this; }
	function nextUntil(){ $this->_call('nextUntil',func_get_args()); return $this; }
	function prevUntil(){ $this->_call('prevUntil',func_get_args()); return $this; }
	function siblings(){ $this->_call('siblings',func_get_args()); return $this; }
	function children(){ $this->_call('children',func_get_args()); return $this; }
	function contents(){ $this->_call('contents',func_get_args()); return $this; }
	function text(){ $this->_call('text',func_get_args()); return $this; }
	function wrapAll(){ $this->_call('wrapAll',func_get_args()); return $this; }
	function wrapInner(){ $this->_call('wrapInner',func_get_args()); return $this; }
	function wrap(){ $this->_call('wrap',func_get_args()); return $this; }
	function unwrap(){ $this->_call('unwrap',func_get_args()); return $this; }
	function append(){ $this->_call('append',func_get_args()); return $this; }
	function prepend(){ $this->_call('prepend',func_get_args()); return $this; }
	function before(){ $this->_call('before',func_get_args()); return $this; }
	function after(){ $this->_call('after',func_get_args()); return $this; }
	function remove(){ $this->_call('remove',func_get_args()); return $this; }
	function phempty(){ $this->_call('empty',func_get_args()); return $this; }
	function phclone(){ $this->_call('clone',func_get_args()); return $this; }
	function html(){ $this->_call('html',func_get_args()); return $this; }
	function replaceWith(){ $this->_call('replaceWith',func_get_args()); return $this; }
	function detach(){ $this->_call('detach',func_get_args()); return $this; }
	function domManip(){ $this->_call('domManip',func_get_args()); return $this; }
	function appendTo(){ $this->_call('appendTo',func_get_args()); return $this; }
	function prependTo(){ $this->_call('prependTo',func_get_args()); return $this; }
	function insertBefore(){ $this->_call('insertBefore',func_get_args()); return $this; }
	function insertAfter(){ $this->_call('insertAfter',func_get_args()); return $this; }
	function replaceAll(){ $this->_call('replaceAll',func_get_args()); return $this; }
	function css(){ $this->_call('css',func_get_args()); return $this; }
	function show(){ $this->_call('show',func_get_args()); return $this; }
	function hide(){ $this->_call('hide',func_get_args()); return $this; }
	function toggle(){ $this->_call('toggle',func_get_args()); return $this; }
	function serialize(){ $this->_call('serialize',func_get_args()); return $this; }
	function serializeArray(){ $this->_call('serializeArray',func_get_args()); return $this; }
	function blur(){ $this->_call('blur',func_get_args()); return $this; }
	function focus(){ $this->_call('focus',func_get_args()); return $this; }
	function focusin(){ $this->_call('focusin',func_get_args()); return $this; }
	function focusout(){ $this->_call('focusout',func_get_args()); return $this; }
	function load(){ $this->_call('load',func_get_args()); return $this; }
	function resize(){ $this->_call('resize',func_get_args()); return $this; }
	function scroll(){ $this->_call('scroll',func_get_args()); return $this; }
	function unload(){ $this->_call('unload',func_get_args()); return $this; }
	function click(){ $this->_call('click',func_get_args()); return $this; }
	function dblclick(){ $this->_call('dblclick',func_get_args()); return $this; }
	function mousedown(){ $this->_call('mousedown',func_get_args()); return $this; }
	function mouseup(){ $this->_call('mouseup',func_get_args()); return $this; }
	function mousemove(){ $this->_call('mousemove',func_get_args()); return $this; }
	function mouseover(){ $this->_call('mouseover',func_get_args()); return $this; }
	function mouseout(){ $this->_call('mouseout',func_get_args()); return $this; }
	function mouseenter(){ $this->_call('mouseenter',func_get_args()); return $this; }
	function mouseleave(){ $this->_call('mouseleave',func_get_args()); return $this; }
	function change(){ $this->_call('change',func_get_args()); return $this; }
	function select(){ $this->_call('select',func_get_args()); return $this; }
	function submit(){ $this->_call('submit',func_get_args()); return $this; }
	function keydown(){ $this->_call('keydown',func_get_args()); return $this; }
	function keypress(){ $this->_call('keypress',func_get_args()); return $this; }
	function keyup(){ $this->_call('keyup',func_get_args()); return $this; }
	function error(){ $this->_call('error',func_get_args()); return $this; }
	function contextmenu(){ $this->_call('contextmenu',func_get_args()); return $this; }
	function hover(){ $this->_call('hover',func_get_args()); return $this; }
	function ajaxStart(){ $this->_call('ajaxStart',func_get_args()); return $this; }
	function ajaxStop(){ $this->_call('ajaxStop',func_get_args()); return $this; }
	function ajaxComplete(){ $this->_call('ajaxComplete',func_get_args()); return $this; }
	function ajaxError(){ $this->_call('ajaxError',func_get_args()); return $this; }
	function ajaxSuccess(){ $this->_call('ajaxSuccess',func_get_args()); return $this; }
	function ajaxSend(){ $this->_call('ajaxSend',func_get_args()); return $this; }
	function fadeTo(){ $this->_call('fadeTo',func_get_args()); return $this; }
	function animate(){ $this->_call('animate',func_get_args()); return $this; }
	function stop(){ $this->_call('stop',func_get_args()); return $this; }
	function finish(){ $this->_call('finish',func_get_args()); return $this; }
	function slideDown(){ $this->_call('slideDown',func_get_args()); return $this; }
	function slideUp(){ $this->_call('slideUp',func_get_args()); return $this; }
	function slideToggle(){ $this->_call('slideToggle',func_get_args()); return $this; }
	function fadeIn(){ $this->_call('fadeIn',func_get_args()); return $this; }
	function fadeOut(){ $this->_call('fadeOut',func_get_args()); return $this; }
	function fadeToggle(){ $this->_call('fadeToggle',func_get_args()); return $this; }
	function offset(){ $this->_call('offset',func_get_args()); return $this; }
	function position(){ $this->_call('position',func_get_args()); return $this; }
	function offsetParent(){ $this->_call('offsetParent',func_get_args()); return $this; }
	function scrollLeft(){ $this->_call('scrollLeft',func_get_args()); return $this; }
	function scrollTop(){ $this->_call('scrollTop',func_get_args()); return $this; }
	function innerHeight(){ $this->_call('innerHeight',func_get_args()); return $this; }
	function height(){ $this->_call('height',func_get_args()); return $this; }
	function outerHeight(){ $this->_call('outerHeight',func_get_args()); return $this; }
	function innerWidth(){ $this->_call('innerWidth',func_get_args()); return $this; }
	function width(){ $this->_call('width',func_get_args()); return $this; }
	function outerWidth(){ $this->_call('outerWidth',func_get_args()); return $this; }
}

class PHTr{
	private $_main=false;
	public $_id;
	private $_type='tr';
	public $jquery;
	public $selector;
	public function __construct() { global $__obj;array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	private function _call($fn,$a) { global $__obj;$args=Array(); for ($i=0;$i<count($a);$i++) array_push($args,is_object($a[$i])&&$a[$i]->_id?Array('_'=>$a[$i]->_id):$a[$i]); array_push($__obj['call'],Array($this->_id,$fn,$args)); }
	function _serialize(){ $out=Array(); foreach ($this as $k=>$v) if (isset($this->$k)) $out[$k]=$this->$k; return $out; }
	function done(){ global $__obj; $this->_main=true; $out=Array('call'=>$__obj['call'],'obj'=>Array()); for ($i=0;$i<count($__obj['obj']);$i++) $out['obj'][$i]=$__obj['obj'][$i]->_serialize(); echo json_encode($out); }
	function init(){ $this->_call('init',func_get_args()); return $this; }
	function size(){ $this->_call('size',func_get_args()); return $this; }
	function toArray(){ $this->_call('toArray',func_get_args()); return $this; }
	function get(){ $this->_call('get',func_get_args()); return $this; }
	function pushStack(){ $this->_call('pushStack',func_get_args()); return $this; }
	function each(){ $this->_call('each',func_get_args()); return $this; }
	function ready(){ $this->_call('ready',func_get_args()); return $this; }
	function slice(){ $this->_call('slice',func_get_args()); return $this; }
	function first(){ $this->_call('first',func_get_args()); return $this; }
	function last(){ $this->_call('last',func_get_args()); return $this; }
	function eq(){ $this->_call('eq',func_get_args()); return $this; }
	function map(){ $this->_call('map',func_get_args()); return $this; }
	function end(){ $this->_call('end',func_get_args()); return $this; }
	function push(){ $this->_call('push',func_get_args()); return $this; }
	function sort(){ $this->_call('sort',func_get_args()); return $this; }
	function splice(){ $this->_call('splice',func_get_args()); return $this; }
	function extend(){ $this->_call('extend',func_get_args()); return $this; }
	function data(){ $this->_call('data',func_get_args()); return $this; }
	function removeData(){ $this->_call('removeData',func_get_args()); return $this; }
	function queue(){ $this->_call('queue',func_get_args()); return $this; }
	function dequeue(){ $this->_call('dequeue',func_get_args()); return $this; }
	function delay(){ $this->_call('delay',func_get_args()); return $this; }
	function clearQueue(){ $this->_call('clearQueue',func_get_args()); return $this; }
	function promise(){ $this->_call('promise',func_get_args()); return $this; }
	function attr(){ $this->_call('attr',func_get_args()); return $this; }
	function removeAttr(){ $this->_call('removeAttr',func_get_args()); return $this; }
	function prop(){ $this->_call('prop',func_get_args()); return $this; }
	function removeProp(){ $this->_call('removeProp',func_get_args()); return $this; }
	function addClass(){ $this->_call('addClass',func_get_args()); return $this; }
	function removeClass(){ $this->_call('removeClass',func_get_args()); return $this; }
	function toggleClass(){ $this->_call('toggleClass',func_get_args()); return $this; }
	function hasClass(){ $this->_call('hasClass',func_get_args()); return $this; }
	function val(){ $this->_call('val',func_get_args()); return $this; }
	function on(){ $this->_call('on',func_get_args()); return $this; }
	function one(){ $this->_call('one',func_get_args()); return $this; }
	function off(){ $this->_call('off',func_get_args()); return $this; }
	function bind(){ $this->_call('bind',func_get_args()); return $this; }
	function unbind(){ $this->_call('unbind',func_get_args()); return $this; }
	function delegate(){ $this->_call('delegate',func_get_args()); return $this; }
	function undelegate(){ $this->_call('undelegate',func_get_args()); return $this; }
	function trigger(){ $this->_call('trigger',func_get_args()); return $this; }
	function triggerHandler(){ $this->_call('triggerHandler',func_get_args()); return $this; }
	function find(){ $this->_call('find',func_get_args()); return $this; }
	function has(){ $this->_call('has',func_get_args()); return $this; }
	function not(){ $this->_call('not',func_get_args()); return $this; }
	function filter(){ $this->_call('filter',func_get_args()); return $this; }
	function is(){ $this->_call('is',func_get_args()); return $this; }
	function closest(){ $this->_call('closest',func_get_args()); return $this; }
	function index(){ $this->_call('index',func_get_args()); return $this; }
	function add(){ $this->_call('add',func_get_args()); return $this; }
	function addBack(){ $this->_call('addBack',func_get_args()); return $this; }
	function andSelf(){ $this->_call('andSelf',func_get_args()); return $this; }
	function parent(){ $this->_call('parent',func_get_args()); return $this; }
	function parents(){ $this->_call('parents',func_get_args()); return $this; }
	function parentsUntil(){ $this->_call('parentsUntil',func_get_args()); return $this; }
	function next(){ $this->_call('next',func_get_args()); return $this; }
	function prev(){ $this->_call('prev',func_get_args()); return $this; }
	function nextAll(){ $this->_call('nextAll',func_get_args()); return $this; }
	function prevAll(){ $this->_call('prevAll',func_get_args()); return $this; }
	function nextUntil(){ $this->_call('nextUntil',func_get_args()); return $this; }
	function prevUntil(){ $this->_call('prevUntil',func_get_args()); return $this; }
	function siblings(){ $this->_call('siblings',func_get_args()); return $this; }
	function children(){ $this->_call('children',func_get_args()); return $this; }
	function contents(){ $this->_call('contents',func_get_args()); return $this; }
	function text(){ $this->_call('text',func_get_args()); return $this; }
	function wrapAll(){ $this->_call('wrapAll',func_get_args()); return $this; }
	function wrapInner(){ $this->_call('wrapInner',func_get_args()); return $this; }
	function wrap(){ $this->_call('wrap',func_get_args()); return $this; }
	function unwrap(){ $this->_call('unwrap',func_get_args()); return $this; }
	function append(){ $this->_call('append',func_get_args()); return $this; }
	function prepend(){ $this->_call('prepend',func_get_args()); return $this; }
	function before(){ $this->_call('before',func_get_args()); return $this; }
	function after(){ $this->_call('after',func_get_args()); return $this; }
	function remove(){ $this->_call('remove',func_get_args()); return $this; }
	function phempty(){ $this->_call('empty',func_get_args()); return $this; }
	function phclone(){ $this->_call('clone',func_get_args()); return $this; }
	function html(){ $this->_call('html',func_get_args()); return $this; }
	function replaceWith(){ $this->_call('replaceWith',func_get_args()); return $this; }
	function detach(){ $this->_call('detach',func_get_args()); return $this; }
	function domManip(){ $this->_call('domManip',func_get_args()); return $this; }
	function appendTo(){ $this->_call('appendTo',func_get_args()); return $this; }
	function prependTo(){ $this->_call('prependTo',func_get_args()); return $this; }
	function insertBefore(){ $this->_call('insertBefore',func_get_args()); return $this; }
	function insertAfter(){ $this->_call('insertAfter',func_get_args()); return $this; }
	function replaceAll(){ $this->_call('replaceAll',func_get_args()); return $this; }
	function css(){ $this->_call('css',func_get_args()); return $this; }
	function show(){ $this->_call('show',func_get_args()); return $this; }
	function hide(){ $this->_call('hide',func_get_args()); return $this; }
	function toggle(){ $this->_call('toggle',func_get_args()); return $this; }
	function serialize(){ $this->_call('serialize',func_get_args()); return $this; }
	function serializeArray(){ $this->_call('serializeArray',func_get_args()); return $this; }
	function blur(){ $this->_call('blur',func_get_args()); return $this; }
	function focus(){ $this->_call('focus',func_get_args()); return $this; }
	function focusin(){ $this->_call('focusin',func_get_args()); return $this; }
	function focusout(){ $this->_call('focusout',func_get_args()); return $this; }
	function load(){ $this->_call('load',func_get_args()); return $this; }
	function resize(){ $this->_call('resize',func_get_args()); return $this; }
	function scroll(){ $this->_call('scroll',func_get_args()); return $this; }
	function unload(){ $this->_call('unload',func_get_args()); return $this; }
	function click(){ $this->_call('click',func_get_args()); return $this; }
	function dblclick(){ $this->_call('dblclick',func_get_args()); return $this; }
	function mousedown(){ $this->_call('mousedown',func_get_args()); return $this; }
	function mouseup(){ $this->_call('mouseup',func_get_args()); return $this; }
	function mousemove(){ $this->_call('mousemove',func_get_args()); return $this; }
	function mouseover(){ $this->_call('mouseover',func_get_args()); return $this; }
	function mouseout(){ $this->_call('mouseout',func_get_args()); return $this; }
	function mouseenter(){ $this->_call('mouseenter',func_get_args()); return $this; }
	function mouseleave(){ $this->_call('mouseleave',func_get_args()); return $this; }
	function change(){ $this->_call('change',func_get_args()); return $this; }
	function select(){ $this->_call('select',func_get_args()); return $this; }
	function submit(){ $this->_call('submit',func_get_args()); return $this; }
	function keydown(){ $this->_call('keydown',func_get_args()); return $this; }
	function keypress(){ $this->_call('keypress',func_get_args()); return $this; }
	function keyup(){ $this->_call('keyup',func_get_args()); return $this; }
	function error(){ $this->_call('error',func_get_args()); return $this; }
	function contextmenu(){ $this->_call('contextmenu',func_get_args()); return $this; }
	function hover(){ $this->_call('hover',func_get_args()); return $this; }
	function ajaxStart(){ $this->_call('ajaxStart',func_get_args()); return $this; }
	function ajaxStop(){ $this->_call('ajaxStop',func_get_args()); return $this; }
	function ajaxComplete(){ $this->_call('ajaxComplete',func_get_args()); return $this; }
	function ajaxError(){ $this->_call('ajaxError',func_get_args()); return $this; }
	function ajaxSuccess(){ $this->_call('ajaxSuccess',func_get_args()); return $this; }
	function ajaxSend(){ $this->_call('ajaxSend',func_get_args()); return $this; }
	function fadeTo(){ $this->_call('fadeTo',func_get_args()); return $this; }
	function animate(){ $this->_call('animate',func_get_args()); return $this; }
	function stop(){ $this->_call('stop',func_get_args()); return $this; }
	function finish(){ $this->_call('finish',func_get_args()); return $this; }
	function slideDown(){ $this->_call('slideDown',func_get_args()); return $this; }
	function slideUp(){ $this->_call('slideUp',func_get_args()); return $this; }
	function slideToggle(){ $this->_call('slideToggle',func_get_args()); return $this; }
	function fadeIn(){ $this->_call('fadeIn',func_get_args()); return $this; }
	function fadeOut(){ $this->_call('fadeOut',func_get_args()); return $this; }
	function fadeToggle(){ $this->_call('fadeToggle',func_get_args()); return $this; }
	function offset(){ $this->_call('offset',func_get_args()); return $this; }
	function position(){ $this->_call('position',func_get_args()); return $this; }
	function offsetParent(){ $this->_call('offsetParent',func_get_args()); return $this; }
	function scrollLeft(){ $this->_call('scrollLeft',func_get_args()); return $this; }
	function scrollTop(){ $this->_call('scrollTop',func_get_args()); return $this; }
	function innerHeight(){ $this->_call('innerHeight',func_get_args()); return $this; }
	function height(){ $this->_call('height',func_get_args()); return $this; }
	function outerHeight(){ $this->_call('outerHeight',func_get_args()); return $this; }
	function innerWidth(){ $this->_call('innerWidth',func_get_args()); return $this; }
	function width(){ $this->_call('width',func_get_args()); return $this; }
	function outerWidth(){ $this->_call('outerWidth',func_get_args()); return $this; }
}

class PHTd{
	private $_main=false;
	public $_id;
	private $_type='td';
	public $jquery;
	public $selector;
	public function __construct() { global $__obj;array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	private function _call($fn,$a) { global $__obj;$args=Array(); for ($i=0;$i<count($a);$i++) array_push($args,is_object($a[$i])&&$a[$i]->_id?Array('_'=>$a[$i]->_id):$a[$i]); array_push($__obj['call'],Array($this->_id,$fn,$args)); }
	function _serialize(){ $out=Array(); foreach ($this as $k=>$v) if (isset($this->$k)) $out[$k]=$this->$k; return $out; }
	function done(){ global $__obj; $this->_main=true; $out=Array('call'=>$__obj['call'],'obj'=>Array()); for ($i=0;$i<count($__obj['obj']);$i++) $out['obj'][$i]=$__obj['obj'][$i]->_serialize(); echo json_encode($out); }
	function init(){ $this->_call('init',func_get_args()); return $this; }
	function size(){ $this->_call('size',func_get_args()); return $this; }
	function toArray(){ $this->_call('toArray',func_get_args()); return $this; }
	function get(){ $this->_call('get',func_get_args()); return $this; }
	function pushStack(){ $this->_call('pushStack',func_get_args()); return $this; }
	function each(){ $this->_call('each',func_get_args()); return $this; }
	function ready(){ $this->_call('ready',func_get_args()); return $this; }
	function slice(){ $this->_call('slice',func_get_args()); return $this; }
	function first(){ $this->_call('first',func_get_args()); return $this; }
	function last(){ $this->_call('last',func_get_args()); return $this; }
	function eq(){ $this->_call('eq',func_get_args()); return $this; }
	function map(){ $this->_call('map',func_get_args()); return $this; }
	function end(){ $this->_call('end',func_get_args()); return $this; }
	function push(){ $this->_call('push',func_get_args()); return $this; }
	function sort(){ $this->_call('sort',func_get_args()); return $this; }
	function splice(){ $this->_call('splice',func_get_args()); return $this; }
	function extend(){ $this->_call('extend',func_get_args()); return $this; }
	function data(){ $this->_call('data',func_get_args()); return $this; }
	function removeData(){ $this->_call('removeData',func_get_args()); return $this; }
	function queue(){ $this->_call('queue',func_get_args()); return $this; }
	function dequeue(){ $this->_call('dequeue',func_get_args()); return $this; }
	function delay(){ $this->_call('delay',func_get_args()); return $this; }
	function clearQueue(){ $this->_call('clearQueue',func_get_args()); return $this; }
	function promise(){ $this->_call('promise',func_get_args()); return $this; }
	function attr(){ $this->_call('attr',func_get_args()); return $this; }
	function removeAttr(){ $this->_call('removeAttr',func_get_args()); return $this; }
	function prop(){ $this->_call('prop',func_get_args()); return $this; }
	function removeProp(){ $this->_call('removeProp',func_get_args()); return $this; }
	function addClass(){ $this->_call('addClass',func_get_args()); return $this; }
	function removeClass(){ $this->_call('removeClass',func_get_args()); return $this; }
	function toggleClass(){ $this->_call('toggleClass',func_get_args()); return $this; }
	function hasClass(){ $this->_call('hasClass',func_get_args()); return $this; }
	function val(){ $this->_call('val',func_get_args()); return $this; }
	function on(){ $this->_call('on',func_get_args()); return $this; }
	function one(){ $this->_call('one',func_get_args()); return $this; }
	function off(){ $this->_call('off',func_get_args()); return $this; }
	function bind(){ $this->_call('bind',func_get_args()); return $this; }
	function unbind(){ $this->_call('unbind',func_get_args()); return $this; }
	function delegate(){ $this->_call('delegate',func_get_args()); return $this; }
	function undelegate(){ $this->_call('undelegate',func_get_args()); return $this; }
	function trigger(){ $this->_call('trigger',func_get_args()); return $this; }
	function triggerHandler(){ $this->_call('triggerHandler',func_get_args()); return $this; }
	function find(){ $this->_call('find',func_get_args()); return $this; }
	function has(){ $this->_call('has',func_get_args()); return $this; }
	function not(){ $this->_call('not',func_get_args()); return $this; }
	function filter(){ $this->_call('filter',func_get_args()); return $this; }
	function is(){ $this->_call('is',func_get_args()); return $this; }
	function closest(){ $this->_call('closest',func_get_args()); return $this; }
	function index(){ $this->_call('index',func_get_args()); return $this; }
	function add(){ $this->_call('add',func_get_args()); return $this; }
	function addBack(){ $this->_call('addBack',func_get_args()); return $this; }
	function andSelf(){ $this->_call('andSelf',func_get_args()); return $this; }
	function parent(){ $this->_call('parent',func_get_args()); return $this; }
	function parents(){ $this->_call('parents',func_get_args()); return $this; }
	function parentsUntil(){ $this->_call('parentsUntil',func_get_args()); return $this; }
	function next(){ $this->_call('next',func_get_args()); return $this; }
	function prev(){ $this->_call('prev',func_get_args()); return $this; }
	function nextAll(){ $this->_call('nextAll',func_get_args()); return $this; }
	function prevAll(){ $this->_call('prevAll',func_get_args()); return $this; }
	function nextUntil(){ $this->_call('nextUntil',func_get_args()); return $this; }
	function prevUntil(){ $this->_call('prevUntil',func_get_args()); return $this; }
	function siblings(){ $this->_call('siblings',func_get_args()); return $this; }
	function children(){ $this->_call('children',func_get_args()); return $this; }
	function contents(){ $this->_call('contents',func_get_args()); return $this; }
	function text(){ $this->_call('text',func_get_args()); return $this; }
	function wrapAll(){ $this->_call('wrapAll',func_get_args()); return $this; }
	function wrapInner(){ $this->_call('wrapInner',func_get_args()); return $this; }
	function wrap(){ $this->_call('wrap',func_get_args()); return $this; }
	function unwrap(){ $this->_call('unwrap',func_get_args()); return $this; }
	function append(){ $this->_call('append',func_get_args()); return $this; }
	function prepend(){ $this->_call('prepend',func_get_args()); return $this; }
	function before(){ $this->_call('before',func_get_args()); return $this; }
	function after(){ $this->_call('after',func_get_args()); return $this; }
	function remove(){ $this->_call('remove',func_get_args()); return $this; }
	function phempty(){ $this->_call('empty',func_get_args()); return $this; }
	function phclone(){ $this->_call('clone',func_get_args()); return $this; }
	function html(){ $this->_call('html',func_get_args()); return $this; }
	function replaceWith(){ $this->_call('replaceWith',func_get_args()); return $this; }
	function detach(){ $this->_call('detach',func_get_args()); return $this; }
	function domManip(){ $this->_call('domManip',func_get_args()); return $this; }
	function appendTo(){ $this->_call('appendTo',func_get_args()); return $this; }
	function prependTo(){ $this->_call('prependTo',func_get_args()); return $this; }
	function insertBefore(){ $this->_call('insertBefore',func_get_args()); return $this; }
	function insertAfter(){ $this->_call('insertAfter',func_get_args()); return $this; }
	function replaceAll(){ $this->_call('replaceAll',func_get_args()); return $this; }
	function css(){ $this->_call('css',func_get_args()); return $this; }
	function show(){ $this->_call('show',func_get_args()); return $this; }
	function hide(){ $this->_call('hide',func_get_args()); return $this; }
	function toggle(){ $this->_call('toggle',func_get_args()); return $this; }
	function serialize(){ $this->_call('serialize',func_get_args()); return $this; }
	function serializeArray(){ $this->_call('serializeArray',func_get_args()); return $this; }
	function blur(){ $this->_call('blur',func_get_args()); return $this; }
	function focus(){ $this->_call('focus',func_get_args()); return $this; }
	function focusin(){ $this->_call('focusin',func_get_args()); return $this; }
	function focusout(){ $this->_call('focusout',func_get_args()); return $this; }
	function load(){ $this->_call('load',func_get_args()); return $this; }
	function resize(){ $this->_call('resize',func_get_args()); return $this; }
	function scroll(){ $this->_call('scroll',func_get_args()); return $this; }
	function unload(){ $this->_call('unload',func_get_args()); return $this; }
	function click(){ $this->_call('click',func_get_args()); return $this; }
	function dblclick(){ $this->_call('dblclick',func_get_args()); return $this; }
	function mousedown(){ $this->_call('mousedown',func_get_args()); return $this; }
	function mouseup(){ $this->_call('mouseup',func_get_args()); return $this; }
	function mousemove(){ $this->_call('mousemove',func_get_args()); return $this; }
	function mouseover(){ $this->_call('mouseover',func_get_args()); return $this; }
	function mouseout(){ $this->_call('mouseout',func_get_args()); return $this; }
	function mouseenter(){ $this->_call('mouseenter',func_get_args()); return $this; }
	function mouseleave(){ $this->_call('mouseleave',func_get_args()); return $this; }
	function change(){ $this->_call('change',func_get_args()); return $this; }
	function select(){ $this->_call('select',func_get_args()); return $this; }
	function submit(){ $this->_call('submit',func_get_args()); return $this; }
	function keydown(){ $this->_call('keydown',func_get_args()); return $this; }
	function keypress(){ $this->_call('keypress',func_get_args()); return $this; }
	function keyup(){ $this->_call('keyup',func_get_args()); return $this; }
	function error(){ $this->_call('error',func_get_args()); return $this; }
	function contextmenu(){ $this->_call('contextmenu',func_get_args()); return $this; }
	function hover(){ $this->_call('hover',func_get_args()); return $this; }
	function ajaxStart(){ $this->_call('ajaxStart',func_get_args()); return $this; }
	function ajaxStop(){ $this->_call('ajaxStop',func_get_args()); return $this; }
	function ajaxComplete(){ $this->_call('ajaxComplete',func_get_args()); return $this; }
	function ajaxError(){ $this->_call('ajaxError',func_get_args()); return $this; }
	function ajaxSuccess(){ $this->_call('ajaxSuccess',func_get_args()); return $this; }
	function ajaxSend(){ $this->_call('ajaxSend',func_get_args()); return $this; }
	function fadeTo(){ $this->_call('fadeTo',func_get_args()); return $this; }
	function animate(){ $this->_call('animate',func_get_args()); return $this; }
	function stop(){ $this->_call('stop',func_get_args()); return $this; }
	function finish(){ $this->_call('finish',func_get_args()); return $this; }
	function slideDown(){ $this->_call('slideDown',func_get_args()); return $this; }
	function slideUp(){ $this->_call('slideUp',func_get_args()); return $this; }
	function slideToggle(){ $this->_call('slideToggle',func_get_args()); return $this; }
	function fadeIn(){ $this->_call('fadeIn',func_get_args()); return $this; }
	function fadeOut(){ $this->_call('fadeOut',func_get_args()); return $this; }
	function fadeToggle(){ $this->_call('fadeToggle',func_get_args()); return $this; }
	function offset(){ $this->_call('offset',func_get_args()); return $this; }
	function position(){ $this->_call('position',func_get_args()); return $this; }
	function offsetParent(){ $this->_call('offsetParent',func_get_args()); return $this; }
	function scrollLeft(){ $this->_call('scrollLeft',func_get_args()); return $this; }
	function scrollTop(){ $this->_call('scrollTop',func_get_args()); return $this; }
	function innerHeight(){ $this->_call('innerHeight',func_get_args()); return $this; }
	function height(){ $this->_call('height',func_get_args()); return $this; }
	function outerHeight(){ $this->_call('outerHeight',func_get_args()); return $this; }
	function innerWidth(){ $this->_call('innerWidth',func_get_args()); return $this; }
	function width(){ $this->_call('width',func_get_args()); return $this; }
	function outerWidth(){ $this->_call('outerWidth',func_get_args()); return $this; }
}

class PHInput{
	private $_main=false;
	public $_id;
	private $_type='input';
	public $jquery;
	public $selector;
	public function __construct() { global $__obj;array_push($__obj['obj'],$this); $this->_id=uniqid(); }
	private function _call($fn,$a) { global $__obj;$args=Array(); for ($i=0;$i<count($a);$i++) array_push($args,is_object($a[$i])&&$a[$i]->_id?Array('_'=>$a[$i]->_id):$a[$i]); array_push($__obj['call'],Array($this->_id,$fn,$args)); }
	function _serialize(){ $out=Array(); foreach ($this as $k=>$v) if (isset($this->$k)) $out[$k]=$this->$k; return $out; }
	function done(){ global $__obj; $this->_main=true; $out=Array('call'=>$__obj['call'],'obj'=>Array()); for ($i=0;$i<count($__obj['obj']);$i++) $out['obj'][$i]=$__obj['obj'][$i]->_serialize(); echo json_encode($out); }
	function init(){ $this->_call('init',func_get_args()); return $this; }
	function size(){ $this->_call('size',func_get_args()); return $this; }
	function toArray(){ $this->_call('toArray',func_get_args()); return $this; }
	function get(){ $this->_call('get',func_get_args()); return $this; }
	function pushStack(){ $this->_call('pushStack',func_get_args()); return $this; }
	function each(){ $this->_call('each',func_get_args()); return $this; }
	function ready(){ $this->_call('ready',func_get_args()); return $this; }
	function slice(){ $this->_call('slice',func_get_args()); return $this; }
	function first(){ $this->_call('first',func_get_args()); return $this; }
	function last(){ $this->_call('last',func_get_args()); return $this; }
	function eq(){ $this->_call('eq',func_get_args()); return $this; }
	function map(){ $this->_call('map',func_get_args()); return $this; }
	function end(){ $this->_call('end',func_get_args()); return $this; }
	function push(){ $this->_call('push',func_get_args()); return $this; }
	function sort(){ $this->_call('sort',func_get_args()); return $this; }
	function splice(){ $this->_call('splice',func_get_args()); return $this; }
	function extend(){ $this->_call('extend',func_get_args()); return $this; }
	function data(){ $this->_call('data',func_get_args()); return $this; }
	function removeData(){ $this->_call('removeData',func_get_args()); return $this; }
	function queue(){ $this->_call('queue',func_get_args()); return $this; }
	function dequeue(){ $this->_call('dequeue',func_get_args()); return $this; }
	function delay(){ $this->_call('delay',func_get_args()); return $this; }
	function clearQueue(){ $this->_call('clearQueue',func_get_args()); return $this; }
	function promise(){ $this->_call('promise',func_get_args()); return $this; }
	function attr(){ $this->_call('attr',func_get_args()); return $this; }
	function removeAttr(){ $this->_call('removeAttr',func_get_args()); return $this; }
	function prop(){ $this->_call('prop',func_get_args()); return $this; }
	function removeProp(){ $this->_call('removeProp',func_get_args()); return $this; }
	function addClass(){ $this->_call('addClass',func_get_args()); return $this; }
	function removeClass(){ $this->_call('removeClass',func_get_args()); return $this; }
	function toggleClass(){ $this->_call('toggleClass',func_get_args()); return $this; }
	function hasClass(){ $this->_call('hasClass',func_get_args()); return $this; }
	function val(){ $this->_call('val',func_get_args()); return $this; }
	function on(){ $this->_call('on',func_get_args()); return $this; }
	function one(){ $this->_call('one',func_get_args()); return $this; }
	function off(){ $this->_call('off',func_get_args()); return $this; }
	function bind(){ $this->_call('bind',func_get_args()); return $this; }
	function unbind(){ $this->_call('unbind',func_get_args()); return $this; }
	function delegate(){ $this->_call('delegate',func_get_args()); return $this; }
	function undelegate(){ $this->_call('undelegate',func_get_args()); return $this; }
	function trigger(){ $this->_call('trigger',func_get_args()); return $this; }
	function triggerHandler(){ $this->_call('triggerHandler',func_get_args()); return $this; }
	function find(){ $this->_call('find',func_get_args()); return $this; }
	function has(){ $this->_call('has',func_get_args()); return $this; }
	function not(){ $this->_call('not',func_get_args()); return $this; }
	function filter(){ $this->_call('filter',func_get_args()); return $this; }
	function is(){ $this->_call('is',func_get_args()); return $this; }
	function closest(){ $this->_call('closest',func_get_args()); return $this; }
	function index(){ $this->_call('index',func_get_args()); return $this; }
	function add(){ $this->_call('add',func_get_args()); return $this; }
	function addBack(){ $this->_call('addBack',func_get_args()); return $this; }
	function andSelf(){ $this->_call('andSelf',func_get_args()); return $this; }
	function parent(){ $this->_call('parent',func_get_args()); return $this; }
	function parents(){ $this->_call('parents',func_get_args()); return $this; }
	function parentsUntil(){ $this->_call('parentsUntil',func_get_args()); return $this; }
	function next(){ $this->_call('next',func_get_args()); return $this; }
	function prev(){ $this->_call('prev',func_get_args()); return $this; }
	function nextAll(){ $this->_call('nextAll',func_get_args()); return $this; }
	function prevAll(){ $this->_call('prevAll',func_get_args()); return $this; }
	function nextUntil(){ $this->_call('nextUntil',func_get_args()); return $this; }
	function prevUntil(){ $this->_call('prevUntil',func_get_args()); return $this; }
	function siblings(){ $this->_call('siblings',func_get_args()); return $this; }
	function children(){ $this->_call('children',func_get_args()); return $this; }
	function contents(){ $this->_call('contents',func_get_args()); return $this; }
	function text(){ $this->_call('text',func_get_args()); return $this; }
	function wrapAll(){ $this->_call('wrapAll',func_get_args()); return $this; }
	function wrapInner(){ $this->_call('wrapInner',func_get_args()); return $this; }
	function wrap(){ $this->_call('wrap',func_get_args()); return $this; }
	function unwrap(){ $this->_call('unwrap',func_get_args()); return $this; }
	function append(){ $this->_call('append',func_get_args()); return $this; }
	function prepend(){ $this->_call('prepend',func_get_args()); return $this; }
	function before(){ $this->_call('before',func_get_args()); return $this; }
	function after(){ $this->_call('after',func_get_args()); return $this; }
	function remove(){ $this->_call('remove',func_get_args()); return $this; }
	function phempty(){ $this->_call('empty',func_get_args()); return $this; }
	function phclone(){ $this->_call('clone',func_get_args()); return $this; }
	function html(){ $this->_call('html',func_get_args()); return $this; }
	function replaceWith(){ $this->_call('replaceWith',func_get_args()); return $this; }
	function detach(){ $this->_call('detach',func_get_args()); return $this; }
	function domManip(){ $this->_call('domManip',func_get_args()); return $this; }
	function appendTo(){ $this->_call('appendTo',func_get_args()); return $this; }
	function prependTo(){ $this->_call('prependTo',func_get_args()); return $this; }
	function insertBefore(){ $this->_call('insertBefore',func_get_args()); return $this; }
	function insertAfter(){ $this->_call('insertAfter',func_get_args()); return $this; }
	function replaceAll(){ $this->_call('replaceAll',func_get_args()); return $this; }
	function css(){ $this->_call('css',func_get_args()); return $this; }
	function show(){ $this->_call('show',func_get_args()); return $this; }
	function hide(){ $this->_call('hide',func_get_args()); return $this; }
	function toggle(){ $this->_call('toggle',func_get_args()); return $this; }
	function serialize(){ $this->_call('serialize',func_get_args()); return $this; }
	function serializeArray(){ $this->_call('serializeArray',func_get_args()); return $this; }
	function blur(){ $this->_call('blur',func_get_args()); return $this; }
	function focus(){ $this->_call('focus',func_get_args()); return $this; }
	function focusin(){ $this->_call('focusin',func_get_args()); return $this; }
	function focusout(){ $this->_call('focusout',func_get_args()); return $this; }
	function load(){ $this->_call('load',func_get_args()); return $this; }
	function resize(){ $this->_call('resize',func_get_args()); return $this; }
	function scroll(){ $this->_call('scroll',func_get_args()); return $this; }
	function unload(){ $this->_call('unload',func_get_args()); return $this; }
	function click(){ $this->_call('click',func_get_args()); return $this; }
	function dblclick(){ $this->_call('dblclick',func_get_args()); return $this; }
	function mousedown(){ $this->_call('mousedown',func_get_args()); return $this; }
	function mouseup(){ $this->_call('mouseup',func_get_args()); return $this; }
	function mousemove(){ $this->_call('mousemove',func_get_args()); return $this; }
	function mouseover(){ $this->_call('mouseover',func_get_args()); return $this; }
	function mouseout(){ $this->_call('mouseout',func_get_args()); return $this; }
	function mouseenter(){ $this->_call('mouseenter',func_get_args()); return $this; }
	function mouseleave(){ $this->_call('mouseleave',func_get_args()); return $this; }
	function change(){ $this->_call('change',func_get_args()); return $this; }
	function select(){ $this->_call('select',func_get_args()); return $this; }
	function submit(){ $this->_call('submit',func_get_args()); return $this; }
	function keydown(){ $this->_call('keydown',func_get_args()); return $this; }
	function keypress(){ $this->_call('keypress',func_get_args()); return $this; }
	function keyup(){ $this->_call('keyup',func_get_args()); return $this; }
	function error(){ $this->_call('error',func_get_args()); return $this; }
	function contextmenu(){ $this->_call('contextmenu',func_get_args()); return $this; }
	function hover(){ $this->_call('hover',func_get_args()); return $this; }
	function ajaxStart(){ $this->_call('ajaxStart',func_get_args()); return $this; }
	function ajaxStop(){ $this->_call('ajaxStop',func_get_args()); return $this; }
	function ajaxComplete(){ $this->_call('ajaxComplete',func_get_args()); return $this; }
	function ajaxError(){ $this->_call('ajaxError',func_get_args()); return $this; }
	function ajaxSuccess(){ $this->_call('ajaxSuccess',func_get_args()); return $this; }
	function ajaxSend(){ $this->_call('ajaxSend',func_get_args()); return $this; }
	function fadeTo(){ $this->_call('fadeTo',func_get_args()); return $this; }
	function animate(){ $this->_call('animate',func_get_args()); return $this; }
	function stop(){ $this->_call('stop',func_get_args()); return $this; }
	function finish(){ $this->_call('finish',func_get_args()); return $this; }
	function slideDown(){ $this->_call('slideDown',func_get_args()); return $this; }
	function slideUp(){ $this->_call('slideUp',func_get_args()); return $this; }
	function slideToggle(){ $this->_call('slideToggle',func_get_args()); return $this; }
	function fadeIn(){ $this->_call('fadeIn',func_get_args()); return $this; }
	function fadeOut(){ $this->_call('fadeOut',func_get_args()); return $this; }
	function fadeToggle(){ $this->_call('fadeToggle',func_get_args()); return $this; }
	function offset(){ $this->_call('offset',func_get_args()); return $this; }
	function position(){ $this->_call('position',func_get_args()); return $this; }
	function offsetParent(){ $this->_call('offsetParent',func_get_args()); return $this; }
	function scrollLeft(){ $this->_call('scrollLeft',func_get_args()); return $this; }
	function scrollTop(){ $this->_call('scrollTop',func_get_args()); return $this; }
	function innerHeight(){ $this->_call('innerHeight',func_get_args()); return $this; }
	function height(){ $this->_call('height',func_get_args()); return $this; }
	function outerHeight(){ $this->_call('outerHeight',func_get_args()); return $this; }
	function innerWidth(){ $this->_call('innerWidth',func_get_args()); return $this; }
	function width(){ $this->_call('width',func_get_args()); return $this; }
	function outerWidth(){ $this->_call('outerWidth',func_get_args()); return $this; }
}

?>